config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # resources 'users', only: %i[new create show update edit]

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout

  # resources :organizations, only: %i[new create index show]

  patch 'password', to: 'passwords#update', as: :edit_password

  resources :organizations, only: %i[new create index show] do
    resources 'users', only: %i[show] do
      resources :metrics, only: %i[new create]
    end
  end
  resources 'users', only: %i[new create edit]

  # Defines the root path route ("/")
  root 'organizations#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates(:email, length: { maximum: 100 })

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships
  has_many :sent_invitations, class_name: 'Invitation', foreign_key: 'sender_id', dependent: :destroy,
                              inverse_of: :sender
  has_many :received_invitations, class_name: 'Invitation', foreign_key: 'recipient_id', dependent: :destroy,
                                  inverse_of: :recipient
  has_many :metrics, dependent: :restrict_with_error

  def admin?(organization_id)
    role_exists?('admin', organization_id)
  end

  def member?(organization_id)
    role_exists?('member', organization_id)
  end

  def owner?(organization_id)
    role_exists?('owner', organization_id)
  end

  private

  def role_exists?(name, organization_id)
    Membership.includes(:role).where(user: self, organization_id:, role: { name: }).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'sessions', only: %i[new create]

  skip_before_action :require_login, only: %i[new create]
  before_action :prevent_registrations, only: %i[new create]

  before_action :require_current_user, only: :edit
  before_action :set_user, only: %i[edit show]

  # GET /users/1
  def show
    set_organization_and_metrics
  end

  # GET /users/new
  def new
    @user = User.new
    @show_frame = :sign_up
  end

  def edit
    @user = current_user
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      @current_user = @user
      set_flash(notice: 'Account created successfully!', notice_type: :success)
      redirect_to root_path
    else
      set_flash(notice: 'Account creation was unsuccessful.', notice_type: :error)
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_organization_and_metrics
    organization_id = params[:organization_id]
    @organization = Organization.find_by(id: organization_id)
    return redirect_to root_path if @organization.blank?

    @metrics = if !current_user.admin?(organization_id) && !current_user.owner?(organization_id)
                 Metric.user_metrics(organization_id:, user_id: current_user_id)
               else
                 Metric.user_metrics(organization_id:, user_id: params[:id])
               end
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def prevent_registrations
    return if @current_user.blank?

    set_flash(notice: 'You already have an account', notice_type: :info)
    redirect_to root_path
  end

  def require_current_user
    return if current_user_id == params[:id].to_i

    redirect_to root_path
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, class: "w-11/12 md:w-6/12 xl:w-4/12" do |form| %>
  <div class="email-password bg-white text-black rounded-2xl p-6 flex flex-col">
    <h3 class="font-bold text-authDarkGray text-2xl mb-3">Email and password</h3>
    <% if form.object&.errors&.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @token.present? %>
      <%= hidden_field_tag :team_invite_token, @token %>
    <% end %>
    <%= form.label :name, class: "flex justify-between items-center border-0 border-b mb-3" do %>
      <span class="font-bold text-authDarkGray">Your name</span>
      <%= form.text_field :name, required: true, autocomplete: "name",  data: { action: "focus->authenticate#focus blur->authenticate#blur"}, class: "form-input border-0 focus:ring-0 w-9/12" %>
    <% end %>
    <%= form.label :email, class: "flex justify-between items-center border-0 border-b mb-3" do %>
      <span class="font-bold text-authDarkGray">E-mail</span>
      <%= form.email_field :email, required: true, autocomplete: "email",  data: { action: "focus->authenticate#focus blur->authenticate#blur"}, class: "form-input border-0 focus:ring-0 w-9/12" %>
    <% end %>
    <%= form.label :password, class: "flex justify-between items-center border-0 border-b mb-3" do %>
      <span class="font-bold text-authDarkGray">Password</span>
      <%= form.password_field :password, required: true,
               title: "Password must be 8 to 50 characters long, contain at least one number, one letter, and one symbol.",
               minlength: "8",
               maxlength: "50",
               autocomplete: "new-password",  data: { action: "focus->authenticate#focus blur->authenticate#blur"}, class: "form-input border-0 focus:ring-0 w-9/12" %>
    <% end %>
    <div class="flex justify-between mt-20">
      <button type="button" data-action="authenticate#navigate" data-target-page="home" data-current-page="sign-up" class="bg-white p-2 w-1/4 rounded-full text-authMidGray font-semibold border border-authLightGray">go back</button>
      <button type="submit" data-turbo-frame="_top" class="bg-authLink p-2 w-1/4 rounded-full text-white font-semibold">Sign Up</button>
    </div>
  </div>
<% end %>

app/views/users/_new.html.erb
<%= turbo_frame_tag "sign-up", class: "#{@show_frame == :sign_up ? 'flex' : 'hidden'} sign-up pt-10 bg-authLink w-full text-white h-screen flex-col items-center justify-items-stretch", data: { 'turbo-action': :advance } do %>
  <%= image_tag "work_hours_logo.png", class: "mb-2 w-9" %>
  <h1 class="font-authLightGray text-base mb-40">Welcome to WorkHours.</h1>
  <%= render "users/form", user: @user %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title do %>
   <title> <%= @current_user.name %> WorkHours Account</title>
<% end %>

<% content_for :heading do %>
  Password change for <%= @current_user.name %>
<% end %>

<div class="flex">
  <div class="w-full sm:w-8/12 md:w-3/4 p-5">
    <%= form_with(model: @user, url: edit_password_path, method: :patch, class: "flex flex-col", data: {controller: :form, action: "turbo:submit-end->form#clear"}) do |form| %>
      <div class="flex rounded-lg shadow-sm mb-4 relative">
        <%= form.label :old_password, 'Old password', class: "cursor-pointer px-4 inline-flex items-center min-w-fit rounded-s-md border border-e-0 border-gray-200 bg-gray-50 text-sm text-gray-500 dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400" %>
        <%= form.password_field :old_password, autocomplete: 'current-password', placeholder: "•••••••••••••••", class: "py-2 px-3 pe-11 block w-full border-gray-200 shadow-sm rounded-e-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", required: true %>
      </div>

      <div class="flex rounded-lg shadow-sm mb-4">
        <%= form.label :password, 'New password', class: "cursor-pointer px-4 inline-flex items-center min-w-fit rounded-s-md border border-e-0 border-gray-200 bg-gray-50 text-sm text-gray-500 dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400" %>
        <%= form.password_field :password, autocomplete: 'new-password', placeholder: "•••••••••••••••", class: "py-2 px-3 pe-11 block w-full border-gray-200 shadow-sm rounded-e-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", required: true %>
      </div>

      <div class="flex rounded-lg shadow-sm mb-4">
        <%= form.label :password_confirmation, 'Confirm new password', class: "cursor-pointer px-4 inline-flex items-center min-w-fit rounded-s-md border border-e-0 border-gray-200 bg-gray-50 text-sm text-gray-500 dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400" %>
        <%= form.password_field :password_confirmation, autocomplete: 'new-password', placeholder: "•••••••••••••••", class: "py-2 px-3 pe-11 block w-full border-gray-200 shadow-sm rounded-e-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", required: true %>
      </div>

      <div>
        <%= form.submit 'Change Password', class: "cursor-pointer py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
      </div>
    <% end %>
    <%= render partial: 'shared/form_notice', locals: { type: 'user_password', errors: nil } %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title do %>
   <title><%= @organization.name %> WorkHours for <%= @user.name %></title>
<% end %>

<% content_for :heading do %>
  <%= @user.name %> WorkHours Timeline
<% end %>

<% if @metrics.present? %>
  <!-- Timeline -->
  <div class="mt-8">
    <% @metrics.each do |metric_group| %>
      <!-- Heading -->
      <div class="ps-2 my-2 first:mt-0">
        <h3 class="my-4 text-sm font-medium uppercase text-gray-700 dark:text-gray-200">
        <%= metric_group.first.strftime "%-d %^b, %Y" %>
        </h3>
      </div>
      <!-- End Heading -->
      <% metric_group.second.each do |metric| %>
        <!-- 'Start Time' Item -->
        <div class="flex gap-x-3">
          <!-- Left Content -->
          <div class="w-16 text-end">
            <span class="text-xs text-gray-500 dark:text-gray-400"><%= metric.start_time.strftime "%I:%M%p" %></span>
          </div>
          <!-- End Left Content -->
          <!-- Icon -->
          <div class="relative last:after:hidden after:absolute after:top-7 after:bottom-0 after:start-3.5 after:w-px after:-translate-x-[0.5px] after:bg-gray-200 dark:after:bg-gray-700">
              <%= render 'shared/clock_9_icon' %>
          </div>
          <!-- End Icon -->

          <!-- Right Content -->
          <div class="grow pt-0.5 pb-8">
            <h3 class="flex gap-x-1.5 font-semibold text-gray-800 dark:text-white">
              Work start time
            </h3>
            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
              Started work <%= start_time_interval(metric.start_time.strftime "%H:%M") %> starting time (9:00 AM).
            </p>
            <button type="button" class="mt-1 -ms-1 p-1 inline-flex items-center gap-x-2 text-xs rounded-lg border border-transparent text-gray-500 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <%= render partial: 'shared/profile_icon', locals: {initials: metric.user_name.first } %>
              <%= metric.user_name %>
            </button>
          </div>
          <!-- End Right Content -->
        </div>
        <!-- End 'Start Time' Item -->

        <!-- 'End Time' Item -->
        <div class="flex gap-x-3">
          <!-- Left Content -->
          <div class="w-16 text-end">
            <span class="text-xs text-gray-500 dark:text-gray-400"><%= metric.end_time.strftime "%I:%M%p" %></span>
          </div>
          <!-- End Left Content -->
          <!-- Icon -->
          <div class="relative last:after:hidden after:absolute after:top-7 after:bottom-0 after:start-3.5 after:w-px after:-translate-x-[0.5px] after:bg-gray-200 dark:after:bg-gray-700">
            <%= render 'shared/clock_5_icon' %>
          </div>
          <!-- End Icon -->

          <!-- Right Content -->
          <div class="grow pt-0.5 pb-8">
            <h3 class="flex gap-x-1.5 font-semibold text-gray-800 dark:text-white">
              Work close time
            </h3>
            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
              Closed for work <%= end_time_interval(metric.end_time.strftime "%H:%M") %> closing time (5:00 PM).
            </p>
            <button type="button" class="mt-1 -ms-1 p-1 inline-flex items-center gap-x-2 text-xs rounded-lg border border-transparent text-gray-500 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <%= render partial: 'shared/profile_icon', locals: {initials: metric.user_name.first } %>
              <%= metric.user_name %>
            </button>
          </div>
          <!-- End Right Content -->
        </div>
        <!-- End 'End Time' Item -->

        <!-- 'Duration' Item -->
        <div class="flex gap-x-3">
          <!-- Left Content -->
          <div class="w-16 text-end">
              <span class="text-xs text-gray-500 dark:text-gray-400"><%= metric.duration.parts[:hours] %> hours</span>
          </div>
          <!-- End Left Content -->
          <!-- Icon -->
          <div class="relative last:after:hidden after:absolute after:top-7 after:bottom-0 after:start-3.5 after:w-px after:-translate-x-[0.5px] after:bg-gray-200 dark:after:bg-gray-700">
            <div class="relative z-10 w-7 h-7 flex justify-center items-center">
            <%= render 'shared/hourglass_icon' %>
            </div>
          </div>
          <!-- End Icon -->
          <!-- Right Content -->
          <div class="grow pt-0.5 pb-8">
            <h3 class="flex gap-x-1.5 font-semibold text-gray-800 dark:text-white">
              Total work time
            </h3>
            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
              Total work time for <%= metric_group.first.strftime "%A, %-d %^b" %> is <%= metric.duration.inspect %>.
            </p>
            <button type="button" class="mt-1 -ms-1 p-1 inline-flex items-center gap-x-2 text-xs rounded-lg border border-transparent text-gray-500 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <%= render partial: 'shared/profile_icon', locals: {initials: metric.user_name.first } %>
              <%= metric.user_name %>
            </button>
          </div>
          <!-- End Right Content -->
        </div>
        <!-- End 'Duration' Item -->
      <% end %>
    <% end %>
  </div>
<% end %>