config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # resources 'users', only: %i[new create show update edit]

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout

  # resources :organizations, only: %i[new create index show]

  patch 'password', to: 'passwords#update', as: :edit_password

  resources :organizations, only: %i[new create index show] do
    resources 'users', only: %i[show] do
      resources :metrics, only: %i[new create]
    end
  end
  resources 'users', only: %i[new create edit]

  # Defines the root path route ("/")
  root 'organizations#index'
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, inverse_of: :organizations
  has_many :invitations, dependent: :destroy
  has_many :metrics, dependent: :restrict_with_error
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :_organizations, only: %i[show index]

  def index; end

  def show
    @organization = @organizations.find(params[:id])

    @organization_id = @organization.id
    @users = @organization.users.distinct
    @metrics = user_aggregated_metrics
  end

  def new; end

  def create
    organization = Organization.create(name: organization_params[:name])

    if organization.save
      owner_role = Role.find_by(name: 'owner')
      organization_member = current_user.memberships.create(role: owner_role, organization:) # TODO: Move to model?

      if organization_member.save
        set_flash(notice: 'Organization successfully created!', notice_type: :success)
        return render :index
      end
    end
    set_flash(notice: organization.errors.first.full_message, notice_type: :error)
    render :index, status: :unprocessable_entity
  end

  private

  def _organizations
    @organizations ||= current_user.organizations
  end

  def user_aggregated_metrics
    condition = [organization_id: @organization_id]

    # scope data to only specific user when user is only a member
    if !current_user.admin?(@organization_id) || !current_user.owner?(@organization_id)
      condition.push(user_id: current_user_id)
    end

    Metric.user_aggregated_metrics(*condition)
  end

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/organizations/_new.html.erb
<%= form_with model: Organization.new, method: :post, class: "mt-8", id: "new-organization-form", data: { controller: :form, action: "turbo:submit-end->form#clear" }   do |form| %>
    <%= form.label :name, "Create a new organization", class: "mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white" %>
    <div class="relative">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 1h12M3 1v16M3 1H2m13 0v16m0-16h1m-1 16H3m12 0h2M3 17H1M6 4h1v1H6V4Zm5 0h1v1h-1V4ZM6 8h1v1H6V8Zm5 0h1v1h-1V8Zm-3 4h2a1 1 0 0 1 1 1v4H7v-4a1 1 0 0 1 1-1Z" />
            </svg>
        </div>
        <%= form.text_field :name, required: true, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Enter the name of your organization" %>
        <%= form.button data: { turbo_frame: "_top" },
        class: "text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
            Create
        <% end %>
    </div>
<% end %>

app/views/organizations/_organization.html.erb
<%= link_to organization.name, organization_path(organization), data: { turbo_frame: "_top" }, class: "block w-full px-4 py-2 border-b border-gray-200 cursor-pointer hover:bg-gray-100 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:border-gray-600 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-500 dark:focus:text-white" %>

app/views/organizations/index.html.erb
<% content_for :title do %>
   <title>Choose or create an Organization on WorkHours</title>
<% end %>
<% content_for :heading do %>
    WorkHours Organizations
<% end %>

<h3 class="my-4 block text-xl font-bold text-gray-800 sm:text-xl dark:text-white">Choose or create an Organization</h3>

<div class="w-full text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white mt-8">
  <%= turbo_frame_tag "organizations" do %>
    <%= render @organizations %>
  <% end %>
  <div>
    <%= render "new" %>
  </div>
</div>

app/views/organizations/new.html.erb
<%= render "new" %>

app/views/organizations/show.html.erb
<% content_for :title do %>
   <title><%= @organization.name %> WorkHours</title>
<% end %>

<% content_for :heading do %>
  <%= @organization.name %> WorkHours
<% end %>

<%= form_with(model: Metric.new, url: organization_user_metrics_url(@organization, @current_user) , class: "flex flex-col mt-8") do |form| %>
  <div class="flex rounded-lg shadow-sm mb-4">
    <%= form.label :start_time, 'Work Start Time', class: "cursor-pointer px-4 inline-flex items-center min-w-fit rounded-s-md border border-e-0 border-gray-200 bg-gray-50 text-sm text-gray-500 dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400" %>
    <%= form.time_field :start_time, class: "py-2 px-3 pe-11 block w-full border-gray-200 shadow-sm rounded-e-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", required: true %>
  </div>

  <div class="flex rounded-lg shadow-sm mb-4">
    <%= form.label :end_time, 'Work Close Time', class: "cursor-pointer px-4 inline-flex items-center min-w-fit rounded-s-md border border-e-0 border-gray-200 bg-gray-50 text-sm text-gray-500 dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400" %>
    <%= form.time_field :end_time, autocomplete: 'new-password', placeholder: "HH:MM AM/PM", class: "py-2 px-3 pe-11 block w-full border-gray-200 shadow-sm rounded-e-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600", required: true %>
  </div>

  <div>
    <%= form.submit 'Submit Work Hours', class: "cursor-pointer py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200 disabled:opacity-50 disabled:pointer-events-none dark:bg-white/10 dark:hover:bg-white/20 dark:text-white dark:hover:text-white dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" %>
  </div>
<% end %>

<div class="flex flex-col border rounded-lg divide-y divide-gray-200 dark:border-gray-700 dark:divide-gray-700 mt-16 p-8  bg-white dark:divide-gray-700 dark:bg-slate-800">
  <div class="-m-1.5 overflow-auto">
    <div class="p-1.5 min-w-full inline-block align-middle">
      <div class="overflow-hidden">
        <div class="table border-collapse table-auto w-full divide-y divide-gray-200 dark:divide-gray-700">
          <div class="table-header-group">
            <div class="table-row">
              <div class="table-cell px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Name</div>
              <div class="table-cell px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Ave. Start Time</div>
              <div class="table-cell px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Ave. Close Time</div>
              <div class="table-cell px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Ave. Work Time</div>
              <div class="table-cell px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Total Work Time</div>
              <div class="table-cell px-6 py-3 text-end text-xs font-medium text-gray-500 uppercase">Action</div>
            </div>
          </div>
          <div class="table-row-group divide-y divide-gray-200 bg-white dark:divide-gray-700 dark:bg-slate-800">
            <% @metrics.each do |metric| %>
                <%= link_to organization_user_path(@organization_id, metric.user_id), class: "table-row odd:bg-white even:bg-gray-100 hover:bg-gray-100 dark:odd:bg-gray-800 dark:even:bg-gray-700 dark:hover:bg-gray-900" do %>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-gray-200"><%= metric.user_name %></div>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200"><%= metric.average_start_time.strftime "%I:%M%p" %></div>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200"><%= metric.average_end_time.strftime "%I:%M%p" %></div>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200"><%= metric.average_duration.inspect %></div>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200"><%= metric.total_duration.inspect %></div>
              <div class="table-cell px-6 py-4 whitespace-nowrap text-end text-sm font-medium">
                <button type="button" class="inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent text-blue-600 hover:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:text-blue-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">View User</button>
              </div>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>